version: '2'

services:
  eureka-server:
    image: sofiaponte/backend_eureka-server:v1
    ports:
      - "8761:8761"

  zuul-server:
    image: sofiaponte/backend_zuul-server:v1
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  microservicio-empresa:
    image: sofiaponte/backend_microservicio-empresa:v1
    ports:
      - "8890:8890"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
      spring.datasource.url: jdbc:postgresql://172.21.252.223:5432/postgresql
      spring.datasource.username: postgresadmin
      spring.datasource.password: Passw0rd2020 

  microservicio-persona:
    image: sofiaponte/backend_microservicio-persona:v1
    ports:
      - "8060:8060"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
      spring.datasource.url: jdbc:postgresql://172.21.252.223/postgresql
      spring.datasource.username: postgresadmin
      spring.datasource.password: Passw0rd2020

  microservicio-transaccion:
    image: sofiaponte/backend_microservicio-transaccion:v1
    ports:
      - "8020:8020"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
      spring.datasource.url: jdbc:postgresql://172.21.252.223:5432/postgresql
      spring.datasource.username: postgresadmin
      spring.datasource.password: Passw0rd2020